Implemented GET request for TELEMETRY
BSU-SUITS-Team/ARSIS-6 pull request #188
Opened 2024-01-20 22:05 UTC by dignojrteogalbo

# Description

Uses the requests library to perform a GET request to `/json_data/teams/0/TELEMETRY.json`.

Fixes #176 

## Bug Fix or Feature

- [ ] Bug
- [X] Feature
- [ ] Other

# Testing Instructions

- [ ] Navigate to `ARSIS-Telemetry-GroundControl/groundcontrol-api/`
- [ ] Run the test suite using `docker-compose up --build tests`
- [ ] The test for `test_get_telemetry` should pass.

## Linting

- [ ] I've linted my code

2024-01-21 15:59 UTC, Aetheris743 requested changes
Do we want to use environment variables at this stage in development? Eventually, it will be useful for deployment and testing

2024-01-21 15:59 UTC, Aetheris743 commented on ARSIS-Telemetry-GroundControl/groundcontrol-api/app/tss.py
> +endpoint = "http://localhost:14141"
```suggestion
from os import getenv
endpoint = getenv("TSS_ENDPOINT")
```

2024-01-21 15:59 UTC, Aetheris743 requested changes
This will make changing environments easier

2024-01-22 23:04 UTC, dignojrteogalbo commented
> This will make changing environments easier

I've added your suggested change and included an environment variable in the `docker-compose.yml` for the tests.

2024-01-28 05:08 UTC, Aetheris743 approved these changes
Looks good to me

2024-01-28 05:09 UTC, merged