Implement readonly WebSocket client for HMD
BSU-SUITS-Team/ARSIS-6 pull request #213
Opened 2024-02-12 10:09 UTC by dignojrteogalbo

# Description

Updated .gitignore to ignore Unity files. Added `WebSocketClient.cs`, `EventManager.cs`, `BaseArsisEvent.cs`, and `Telemetry.cs` classes.

Fixes #205

## Bug Fix or Feature

- [ ] Bug
- [X] Feature
- [ ] Other

# Testing Instructions

From the project directory (e.g. `ARSIS/`)

- [ ] `cd ARSIS-Telemetry-GroundControl`
- [ ] `docker-compose up --build`
- [ ] Start the Unity project
- [ ] Press play on the Unity editor
- [ ] Debug console should print out received events
- [ ] Debug console prints out `Telemetry event` for telemetry events
- [ ] Debug console prints out `ARSIS.EventManager.BaseArsisEvent` for all other unimplemented events

## Linting

- [ ] I've linted my code

2024-02-12 21:27 UTC, cburnout commented
Can we do this in 2 different PRs. one to update the git ignore and the tracked files and one for just the websocket?

2024-02-12 21:46 UTC, dignojrteogalbo commented
Yeah I can open another one to commit the updated .gitignore and then merge this branch to master once the other once gets in.

2024-02-13 01:39 UTC, cburnout requested changes

2024-02-13 01:39 UTC, cburnout commented on ARSIS-Unity/Assets/Scripts/EventManager/WebSocketClient.cs
> +            if (unknownEvent.type.Equals(Telemetry.Type))
I think here we can create a dictionary or do something that does this not by checking the type but by using generics to unjson it.

2024-02-16 17:48 UTC, Aetheris743 commented on ARSIS-Unity/Assets/Scripts/EventManager/EventTypes/BaseArsisEvent.cs
> +        };
What would you think about putting somthing like this in the `EventManager` to autogenerate the types?
```csharp
...
// stores reflection generated types
private Dictionary<string, Type> eventDictionary = new Dictionary<string, Type>();
```
```csharp
private struct TmpFormat
{
    public string type;
    public string data;
}

private static string EncodeEvent(BaseArsisEvent eventToEncode)
{
    string name = eventToEncode.GetType().Name;
    string body = JsonUtility.ToJson(eventToEncode);
    return JsonUtility.ToJson(new TmpFormat { type = name, data = body });
}

private BaseArsisEvent DecodeEvent(string json)
{
    TmpFormat tmp = JsonUtility.FromJson<TmpFormat>(json);
    Type type = eventDictionary[tmp.type];
    return (BaseArsisEvent)JsonUtility.FromJson(tmp.data, type);
}

```
```csharp

void Start() {
    ...
    // initalize the dict
    Type target = typeof(BaseArsisEvent);
    Assembly assembly = Assembly.GetAssembly(target);

    var types = assembly.GetTypes().Where(t => t.IsSubclassOf(target));

    foreach (var type in types)
    {
        eventDictionary.Add(type.Name, type);
    }
    ...
}

```

2024-02-16 17:57 UTC, Aetheris743 commented on ARSIS-Unity/Assets/Scripts/EventManager/EventTypes/BaseArsisEvent.cs
> +        };
nvm, I think I missed your `DoReflection` method

2024-02-17 20:25 UTC, cburnout approved these changes

2024-02-17 20:26 UTC, merged